### PR TITLE
Generalize HTTP client code

### PR DESCRIPTION
**Pull request by djoreilly**
Allow verbs other than GET.
Provide parameter for request body.
Check range of status codes for success.

### CODE REVIEW

**Review by skazi0 — CHANGES_REQUESTED** [review]
We also need query params (see https://github.com/SUSE/connect-ng/pull/4/commits/5ec7e83892a833ea587b12895b03ea8a0dc87c63)

**Comment by djoreilly** [comment]
> We also need query params (see [5ec7e83](https://github.com/SUSE/connect-ng/commit/5ec7e83892a833ea587b12895b03ea8a0dc87c63))

Good point. I'll wait until your changes are merged and rebase.

**Comment by skazi0** [comment]
@djoreilly I think it would be better if you add params handling to your change (as it's more generic)... and then I'll rebase :o)

**Comment by djoreilly** [comment]
> @djoreilly I think it would be better if you add params handling to your change (as it's more generic)... and then I'll rebase :o)

ok will do

**Review by skazi0 — APPROVED** [review]
tested in https://github.com/SUSE/connect-ng/pull/4

**Review by skazi0 — APPROVED** [review]

**Review by skazi0 — APPROVED** [review]

**Review by skazi0 — APPROVED** [review]

**Pull request merged**
