### PR TITLE
Add zypper search-packages plugin

### PR DESCRIPTION
**Pull request by skazi0**
port of https://github.com/jsrain/zypper-search-packages

### CODE REVIEW

**Comment by skazi0** [comment]
NOTE: the "TEMP" commit is extracted to https://github.com/SUSE/connect-ng/pull/95. It should be removed from here when that PR is merged.

**Review by djoreilly — COMMENTED** [review]
When testing the options from the man page, it seems `-d` and `-g` don't work the same as the ruby version.

**Comment by skazi0** [comment]
@djoreilly `-d` might be affected by this: https://github.com/jsrain/zypper-search-packages/pull/6
I added `-g` which was missing.

**Comment by djoreilly** [comment]
> @djoreilly `-d` might be affected by this: [jsrain/zypper-search-packages#6](https://github.com/jsrain/zypper-search-packages/pull/6) I added `-g` which was missing.

okay, does the `-d` need to be changed to `-s` in suseconnect/searchPackagesUsage.txt ?

**Comment by skazi0** [comment]
> okay, does the `-d` need to be changed to `-s` in suseconnect/searchPackagesUsage.txt ?
good catch! updated

**Review by djoreilly — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
