### PR TITLE
auto import keys flag comes before zypper action bsc#1219004

### PR DESCRIPTION
**Pull request by rtamalin**
When including the --gpg-auto-import-keys flag in the zypper command line, it must be placed before the action, e.g. ref, rather than after as it is a global flag.

Found while testing DMS migrations after switching to suseconnect-ng based zypper migration workflow.

### CODE REVIEW

**Comment by rtamalin** [comment]
Note that this is an updated version of the fix proposed in PR#220, this time proposed from a branch in the main repo, rather than a personal form, so the feature tests CI should be able to run now.

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

I already tested this in the old pull request!

**Comment by felixsch** [comment]
It would be nice to have a Changelog entry added for this bug

**Comment by rtamalin** [comment]
> It would be nice to have a Changelog entry added for this bug

Happy to do so if there is a recommended procedure for doing so.

Looking at [suseconnect-ng.changes](build/packaging/suseconnect-ng.changes) it appears to be maintained as part of creating a specific version release.

**Comment by rtamalin** [comment]
> > It would be nice to have a Changelog entry added for this bug
> 
> Happy to do so if there is a recommended procedure for doing so.
> 
> Looking at [suseconnect-ng.changes](build/packaging/suseconnect-ng.changes) it appears to be maintained as part of creating a specific version release.

Looking at @guangyee's PR#210 changes I see a changelog entry being added for a v1.9.0 release; I'm happy to add a similar entry if that is the best way to go forward?

**Pull request merged**
