### PR TITLE
Run integration tests

### PR DESCRIPTION
**Pull request by JanZerebecki**
This runs the cucumber integration tests from the ruby version of
suseconnect on suseconnect-ng.

### CODE REVIEW

**Comment by JanZerebecki** [comment]
https://github.com/SUSE/connect/pull/460 adds SLE_15_SP3 to the tests.

**Comment by JanZerebecki** [comment]
https://github.com/SUSE/scc-provisioning/pull/445 installs the required obs services on build hosts

**Comment by JanZerebecki** [comment]
Passes fully now: https://ci.suse.de/job/scc-connect-ng-prs/job/cucumber/14/

**Review by djoreilly — CHANGES_REQUESTED** [review]
This should be failing at least a few tests, like --version. I think it is running the Ruby from 
 /tmp/connect/bin/SUSEConnect

**Comment by JanZerebecki** [comment]
Good find. Deleting that file fixed it.

**Review by djoreilly — APPROVED** [review]
lgtm

**Pull request merged**
